#ifndef GUARD_CONSTANTS_LANGUAGES_H
#define GUARD_CONSTANTS_LANGUAGES_H

enum Languages {
    LANGUAGE_JAPANESE,
    LANGUAGE_ENGLISH,
    LANGUAGE_GERMAN,
    LANGUAGE_FRENCH,
    LANGUAGE_ITALIAN,
    LANGUAGE_SPANISH,

    LANGUAGE_COUNT
};

#endif // GUARD_CONSTANTS_LANGUAGES_H